// GENERATED by scripts/generate-rule-aliases.mjs — do not edit by hand.
// Maps v2 English field/column names to seed rule ids / seed categories.
// Validated against MVP catalog + v2 runtime tables (3 documented drifts follow
// the MVP catalog per spec: Non-Standard Assets category, Environmental Noise
// and Microphone Friction Noise scores).

export const RULE_ALIASES: Record<string, string> = {
  'Tilted/Crooked Camera': 'camera-inclinada-torta',
  'Excessive/Low Headroom': 'muito-pouco-teto',
  'Poor Logo Framing': 'logo-mal-enquadrada',
  'Visible Backdrop Limits': 'limites-do-banner-painel-chroma-visiveis',
  'Subject Chroma Cutoff': 'professor-cortado-no-chroma',
  'Subject Too Close/Far': 'professor-muito-proximo-distante-da-camera',
  'Camera Shake/Instability': 'camera-tremendo-instavel',
  'Subject Off-Center': 'professor-descentralizado',
  'Subject Blocking Virtual TV': 'professor-a-frente-da-tv-virtual',
  'Overexposed (Clipping)': 'iluminacao-estourando',
  'Underexposed (Dark)': 'iluminacao-fraca',
  'Uneven Lighting': 'iluminacao-nao-uniforme',
  'Harsh Shadows': 'sombras',
  'Incorrect Color Temp (Warm/Cold)': 'temperatura-de-luz-quente-fria',
  Flicker: 'flicker',
  'Natural Light fluctuation': 'luz-natural-oscilacao',
  'Glasses Reflection (Lighting)': 'reflexo-de-iluminacao-nos-oculos',
  'Glasses Reflection (Monitor)': 'reflexo-de-retorno-nos-oculos',
  'Background Reflection': 'reflexo-de-equipamentos-no-vidro-tv-ao-fundo',
  'Out of Focus': 'imagem-desfocada',
  'Low Resolution/Bitrate': 'resolucao-baixa',
  'Color Mismatch': 'cor-desconforme',
  'Layer/Composition Error': 'camada-do-material-com-irregularidades',
  'A/V Desync': 'video-dessincronizado',
  'Exposure Hunting': 'exposicao-oscilando',
  'Focus Hunting': 'foco-oscilando',
  'Video Freezing/Stutter': 'video-travando',
  'Dropped Frames': 'queda-de-fps',
  'Non-Standard Assets': 'material-fora-dos-padroes',
  'Incorrect Chroma BG': 'bg-chroma-fora-do-padrao',
  'Asset Misaligned on Virtual TV': 'material-mal-encaixado-na-tv-virtual',
  'Chroma Key Failure': 'falhas-no-chroma',
  'Non-Standard Scenery': 'sem-cenario-padrao',
  'Visual Pollution': 'poluicao-visual',
  'Damaged Scenery': 'cenario-avariado',
  'Audio Clipping (Peaking)': 'audio-estourando',
  'Low Volume': 'volume-baixo',
  'Distorted Audio': 'audio-deformado',
  'HVAC Noise': 'ruido-de-ar-condicionado',
  'Environmental Noise': 'ruidos-ambiente',
  'Microphone Friction Noise': 'ruido-de-atrito-no-microfone',
  'Interference/Static': 'audio-com-interferencia',
  'Excessive Reverb': 'reverberacao',
};

/** v2 score column label → seed categoryId */
export const SCORE_COLUMN_TO_CATEGORY: Record<string, string> = {
  'FRAMING SCORE': 'ENQUADRAMENTO',
  'LIGHTING SCORE': 'ILUMINAÇÃO',
  'VIDEO SCORE': 'OUTROS',
  'SCENERY SCORE': 'CENÁRIO',
  'AUDIO SCORE': 'ÁUDIO',
};

/** v2 total score column */
export const FINAL_SCORE_COLUMN = 'FINAL SCORE';
